title: David Guida
description: > # this means to ignore newlines until "baseurl:"
  A little bit of software architecture, design patterns and game programming. Focusing on .NET Core, ASP.NET, C#, Blazor, Azure.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.davidguida.net" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: DavideGuida82

# Author Settings
author: David Guida # add your name
author-img: david-guida.jpg # add your photo
about-author: my personal thoughts about life, coding, the universe and everything.
social-twitter: DavideGuida82
social-github: mizrael 
social-linkedin: davideguida
social-youtube: UC1TKz3-S7ns3xi2H0hFjjjQ

# Disqus
discus-identifier: www-davidguida-net

# Tracker
analytics: G-WY9NJRPPGW # Google Analytics

# google ads
google_ads: ca-pub-2371802329711833

# bookkme: 07063785

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed

paginate: 4
paginate_path: "/page/:num"

jekyll-minifier:
  exclude: 'atom.xml'

exclude: ["node_modules", "README.md", "LICENSE", "gulpfile.js", "package.json", "package-lock.json","yarn.lock", "wp-config"]
